---
title: "week2lecture"
date: "2024-01-24"
output:
  github_document:
      toc: true
      toc_depth: 2
      fig_width: 7
      fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## read in data
```{r}
df <- readRDS("data/wk2_stocks.rds")
str(df)
```


## statistics
+ the cumulative returns of the S&P index during this period is `r round(sum(df$SPY_returns) * 100, 2)`%
+ the average daily returns of the S&P index during this period is `r round(mean(df$SPY_returns) * 100, 2)`%
+ the standard deviation of the daily returns of the S&P index during this period is `r round(sd(df$SPY_returns) * 100, 2)`%


## plot of s&p prices
```{r, message = FALSE}
library(tidyverse)
ggplot(data = df, aes(x = date, y = SPY_prices)) +
  geom_line()
```


## plot of s&p yearly returns
```{r}
df %>%
  mutate(year = year(date)) %>%
  filter(year <= 2023) %>%
  group_by(year) %>%
  summarise(yr_return = sum(SPY_returns)) %>%
  
  ggplot(aes(x = year, y = yr_return)) +
  geom_col()
```